# Generated by Django 5.0.6 on 2024-06-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festicon', '0002_service_user_alter_service_provider_serviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
