# Generated by Django 5.0.6 on 2024-06-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festicon', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
