# Generated by Django 5.0.6 on 2024-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festicon', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
